---
window:
  width:  1200
  height: 700
  title:  'Ludum Dare 41!'

game:
  colors:
    background:             0xff_cccccc
  background_z_index:       0
  background_image_z_index: 5
  valid_prompt_keys:
    - A
    - S
    - D
    - F
    - H
    - J
    - K
    - L
    - Q
    - W
    - E
    - R
    - U
    - I
    - O
  fonts:
    game_over_text:
      size:                        80
      background_size:
        width:                     384
        height:                    96
      colors:
        foreground:                0xff_ad0d0d
        background:                0xaa_aaaaaa
      z_indexes:
        foreground:                250
        background:                200
    game_over_scores:
      size:                        32
      background_size:
        width:                     512
        height:                    64
      background_color:            0xaa_aaaaaa
      foreground_colors:
        name:   0xff_000000
        time:   0xff_5400a8
        points: 0xff_5400a8
        kills:  0xff_5400a8
      z_indexes:
        foreground:                250
        background:                200
      padding_y:                   8

instance_defaults:
  z_index:  50
  color:    0xff_000000
  position:
    x:      0
    y:      0
  size:
    width:  0
    height: 0

enemies:
  defaults:
    size:
      width:        32
      height:       48
    z_index:        50
    speed:          4
    damage:         1
    health:         1
    max_health:     1
    points:         10
    amount_of_keys: 1
  health_bar:
    relative_position:
      x:            0.0
      y:            0.0
    relative_size:
      width:        1.0
      height:       0.25
    colors:
      foreground:   0xff_9b0000
      background:   0xff_444444
    z_indexes:
      background:   60
      foreground:   70
    border_padding:
      x:            1
      y:            1
  zombie:
    size:
      width:        32
      height:       48
    speed:          3
    damage:         1
    animation:
      delay:        0.1
      image_order:
        - Zombie_0
        - Zombie_1
        - Zombie_2
    points:         5
    amount_of_keys: 1
  wizard:
    size:
      width:        32
      height:       48
    speed:          3
    damage:         2
    animation:
      delay:        0.25
      image_order:
        - Wizard_0
        - Wizard_1
        - Wizard_2
    points:         5
    amount_of_keys: 2
  big:
    size:
      width:        80
      height:       96
    speed:          2
    damage:         2
    animation:
      delay:        0.5
      image_order:
        - Big_0
        - Big_1
        - Big_2
        - Big_3
    points:         15
    amount_of_keys: 2

prompt:
  y_offset:           16
  colors:
    inactive:
      background:       0xff_888888
      foreground:       0xff_000000
    active:
      background:       0xff_888888
      foreground:       0xff_a51515
  z_indexes:
    background:         60
    foreground:         65
  size:
    height:             28
    width:              64
  font_size:            28

fort:
  size:
    width:              320
    height:             380
  z_index:              10
  health:               20
  max_health:           20
  health_bar:
    relative_position:
      x:                0.5
      y:                0.75
    relative_size:
      width:            0.75
      height:           0.1
    colors:
      foreground:       0xff_9b0000
      background:       0xff_888888
    z_indexes:
      background:       20
      foreground:       30
    border_padding:
      x:                4
      y:                4
  animation:
    delay:              0.1
    image_order:
      - Fort_0
      - Fort_1
      - Fort_0
      - Fort_2

lines:
  x_offset: 128
  width:    80
  color:    0x66_444444
  z_index:  40

clusters:
  amount_of_beats:            16
  defaults:
    spawn_position_y_padding: 96
  rapid:
    delay:                    0.5
  alternate:
    delay:                    1.0
  double_alternate:
    delay:                    0.5
  quad_double_alternate:
    delay:                    0.75
  random:
    delay:                    1.0
  rapid_wizards:
    delay:                    1.0
  alternate_wizards:
    delay:                    1.25

difficulty:
  base:
    speed_multiplier:          1.0
    delay_multiplier:          1.0
  speed_multiplier_increment:  0.05
  delay_multiplier_decrement:  0.05

score:
  font_size:    32
  text_padding: 4
  colors:
    foreground: 0x66_000000
    background: 0x66_cccccc
  z_indexes:
    foreground: 110
    background: 100
  background_size:
    width:  128
    height: 32
...
