---
window:
  width:  960
  height: 560
  title:  'Ludum Dare 41!'

game:
  colors:
    background:       0xff_cccccc
  background_z_index: 0

instance_defaults:
  z_index: 0
  color:   0xff_000000

entity_defaults:
  z_index: 20

enemies:
  defaults:
    size:
      width:  64
      height: 128
    z_index:  20
    move_step:
      x:      4
      y:      0
    damage:   10
  normal:
    move_step:
      x:      4
      y:      0
    damage:   10

fort:
  size:
    width:              240
    height:             500
  z_index:              10
  health:               100
  max_health:           100
  health_bar:
    relative_position:
      x:                0.5
      y:                0.75
    size:
      width:            64
      height:           24
    colors:
      foreground:       0xff_ff0000
      background:       0xff_eeeeee
    z_indexes:
      background: 20
      foreground: 30

clusters:
  defaults:
    spawn_position_y_min: 64
...
