---
window:
  width:  960
  height: 560
  title:  'Ludum Dare 41!'

game:
  colors:
    background:             0xff_cccccc
  background_z_index:       0
  background_image_z_index: 5
  valid_prompt_keys:
    - A
    - S
    - D
    - F
    - H
    - J
    - K
    - L
    - Q
    - W
    - E
    - R
    - U
    - I
    - O

instance_defaults:
  z_index:  50
  color:    0xff_000000
  position:
    x:      0
    y:      0
  size:
    width:  0
    height: 0

enemies:
  defaults:
    size:
      width:        32
      height:       48
    z_index:        50
    speed:
      x:            4
      y:            0
    damage:         1
    health:         1
    max_health:     1
    points:         10
  health_bar:
    relative_position:
      x:            0.0
      y:            0.0
    relative_size:
      width:        1.0
      height:       0.25
    colors:
      foreground:   0xff_ff0000
      background:   0xff_444444
    z_indexes:
      background:   60
      foreground:   70
    border_padding:
      x:            1
      y:            1
  normal:
    size:
      width:        32
      height:       48
    speed:
      x:            3
      y:            0.0
    damage:         1
    health:         1
    max_health:     1
    animation:
      delay:        0.5
      image_order:
        - Small
    points:         5

prompt:
  y_offset:           16
  colors:
    inactive:
      background:       0xff_888888
      foreground:       0x99_dddddd
      foreground_shift: 0x99_ffdddd
    active:
      background:       0xff_666666
      foreground:       0xff_2a74fc
      foreground_shift: 0xff_ff74fc
  z_indexes:
    background:         60
    foreground:         65
  size:
    height:             24
    width:              64
  font_size:            24

fort:
  size:
    width:              240
    height:             500
  z_index:              10
  health:               10
  max_health:           10
  health_bar:
    relative_position:
      x:                0.5
      y:                0.75
    relative_size:
      width:            0.75
      height:           0.1
    colors:
      foreground:       0xff_ff0000
      background:       0xff_888888
    z_indexes:
      background:       20
      foreground:       30
    border_padding:
      x:                4
      y:                4

lines:
  x_offset: 128
  width:    64
  color:    0x99_444444
  z_index:  40

clusters:
  defaults:
    spawn_position_y_min: 64

difficulty:
  base:
    speed_multiplier:
      x: 1.0
      y: 1.0
  speed_multiplier_increase_step:
    x:   0.25
    y:   0.0

score:
  font_size:    32
  text_padding: 4
  colors:
    foreground: 0x66_000000
    background: 0x66_cccccc
  z_indexes:
    foreground: 110
    background: 100
  background_size:
    width:  128
    height: 32
...
