---
window:
  width:  960
  height: 560
  title:  'Ludum Dare 41!'

game:
  colors:
    background:       0xff_cccccc
  background_z_index: 0

instance_defaults:
  z_index: 0
  color:   0xff_000000

entity_defaults:
  z_index: 50

enemies:
  defaults:
    size:
      width:  32
      height: 48
    z_index:  50
    move_step:
      x:      4
      y:      0
    damage:   10
    health_bar:
      relative_position:
        x:          0.0
        y:          0.0
      relative_size:
        width:      1.0
        height:     0.1
      colors:
        foreground: 0xff_ff0000
        background: 0xff_888888
      z_indexes:
        background: 60
        foreground: 70
      border_padding:
        x:          2
        y:          2
  normal:
    move_step:
      x:            4
      y:            0.0
    damage:         10
    animation:
      delay:        0.5
      image_order:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8

fort:
  size:
    width:              240
    height:             500
  z_index:              10
  health:               99000
  max_health:           99000
  health_bar:
    relative_position:
      x:                0.5
      y:                0.75
    relative_size:
      width:            0.75
      height:           0.1
    colors:
      foreground:       0xff_ff0000
      background:       0xff_888888
    z_indexes:
      background:       20
      foreground:       30
    border_padding:
      x:                4
      y:                4

clusters:
  defaults:
    spawn_position_y_min: 64
...
